
-- ---------------------------------------------------------
-- Table structure for SEKOLAH
-- ---------------------------------------------------------
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `sekolah`;
CREATE TABLE `sekolah` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `puskesmas_id` bigint unsigned NOT NULL,
  `npsn` varchar(20) NOT NULL UNIQUE,
  `nama_sekolah` varchar(100) NOT NULL,
  `jenjang` enum('SD','SMP','SMA','SMK') NOT NULL,
  `negeri_swasta` enum('Negeri','Swasta') NOT NULL,
  `alamat` text,
  `kelurahan` varchar(100),
  `kecamatan` varchar(100),
  `kepala_sekolah` varchar(100),
  `jumlah_siswa` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `fk_sekolah_puskesmas` (`puskesmas_id`),
  CONSTRAINT `fk_sekolah_puskesmas` FOREIGN KEY (`puskesmas_id`) REFERENCES `puskesmas` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO `sekolah` (`id`, `puskesmas_id`, `npsn`, `nama_sekolah`, `jenjang`, `negeri_swasta`, `alamat`, `kelurahan`, `kecamatan`, `kepala_sekolah`, `jumlah_siswa`) VALUES
(1, 1, '30462241', 'SD MIT Kecamatan Wowo', 'SD', 'Negeri', 'Jl. Juanda No. 138, Kelurahan Popo, Kecamatan Wowo', 'Kelurahan Popo', 'Kecamatan Wowo', 'Zainal Arif Manurung', 60),
(2, 1, '30493791', 'SD Yale Kecamatan Wowo', 'SD', 'Negeri', 'Jl. Basuki Rahmat No. 21, Kelurahan Lili, Kecamatan Wowo', 'Kelurahan Lili', 'Kecamatan Wowo', 'Dani Aditya Irawan', 49),
(3, 1, '30490720', 'SD Yale Kecamatan Wowo A', 'SD', 'Negeri', 'Jl. Mulawarman No. 21, Kelurahan Popo, Kecamatan Wowo', 'Kelurahan Popo', 'Kecamatan Wowo', 'Eko Tio Budiman', 55),
(4, 1, '30434121', 'SD Yale Kecamatan Wowo B', 'SD', 'Negeri', 'Jl. Bung Tomo No. 89, Kelurahan Mumu, Kecamatan Wowo', 'Kelurahan Mumu', 'Kecamatan Wowo', 'Rian Tio Sari', 39),
(5, 1, '30435843', 'SD Cambridge Kecamatan Wowo', 'SD', 'Negeri', 'Jl. Wahid Hasyim No. 58, Kelurahan Mumu, Kecamatan Wowo', 'Kelurahan Mumu', 'Kecamatan Wowo', 'Rian Pratama', 48),
(6, 1, '30469519', 'SMP Gaul Kecamatan Wowo', 'SMP', 'Negeri', 'Jl. Basuki Rahmat No. 73, Kelurahan Mimi, Kecamatan Wowo', 'Kelurahan Mimi', 'Kecamatan Wowo', 'Joko Pramono', 39),
(7, 1, '30460270', 'SMP Pintar Kecamatan Wowo', 'SMP', 'Negeri', 'Jl. Cipto Mangunkusumo No. 55, Kelurahan Pepe, Kecamatan Wowo', 'Kelurahan Pepe', 'Kecamatan Wowo', 'Rudi Kurniawan', 47),
(8, 1, '30403829', 'SMA Koboh Kecamatan Wowo', 'SMA', 'Swasta', 'Jl. Aminah Syukur No. 49, Kelurahan Pepe, Kecamatan Wowo', 'Kelurahan Pepe', 'Kecamatan Wowo', 'Ilham Tanjung', 42),
(9, 1, '30409346', 'SMA Unggul Kecamatan Wowo', 'SMA', 'Swasta', 'Jl. Untung Suropati No. 26, Kelurahan Mimi, Kecamatan Wowo', 'Kelurahan Mimi', 'Kecamatan Wowo', 'Raka Hidayat', 50),
(10, 1, '30431877', 'SMK Kreatif Kecamatan Wowo', 'SMK', 'Negeri', 'Jl. Pemuda No. 120, Kelurahan Pepe, Kecamatan Wowo', 'Kelurahan Pepe', 'Kecamatan Wowo', 'Iwan Hasibuan', 45),
(11, 2, '30437086', 'SD MIT Kecamatan Hehe', 'SD', 'Negeri', 'Jl. Kadrie Oening No. 113, Kelurahan Coco, Kecamatan Hehe', 'Kelurahan Coco', 'Kecamatan Hehe', 'Rizal Heri Simanjuntak', 50),
(12, 2, '30457236', 'SD Oxford Kecamatan Hehe', 'SD', 'Negeri', 'Jl. RE Martadinata No. 60, Kelurahan Huhu, Kecamatan Hehe', 'Kelurahan Huhu', 'Kecamatan Hehe', 'Agus Wicaksono', 55),
(13, 2, '30441245', 'SD Columbia Kecamatan Hehe', 'SD', 'Negeri', 'Jl. KH. Harun Nafsi No. 20, Kelurahan Coco, Kecamatan Hehe', 'Kelurahan Coco', 'Kecamatan Hehe', 'Aditya Muhammad Haryanto', 48),
(14, 2, '30493913', 'SD MIT Kecamatan Hehe A', 'SD', 'Swasta', 'Jl. RE Martadinata No. 93, Kelurahan Cucu, Kecamatan Hehe', 'Kelurahan Cucu', 'Kecamatan Hehe', 'Roni Rian Saefullah', 57),
(15, 2, '30410614', 'SD Berkeley Kecamatan Hehe', 'SD', 'Negeri', 'Jl. Aminah Syukur No. 78, Kelurahan Cici, Kecamatan Hehe', 'Kelurahan Cici', 'Kecamatan Hehe', 'Iwan Zainal Mulyono', 42),
(16, 2, '30458562', 'SMP Juara Kecamatan Hehe', 'SMP', 'Swasta', 'Jl. S. Parman No. 126, Kelurahan Didi, Kecamatan Hehe', 'Kelurahan Didi', 'Kecamatan Hehe', 'Yudi Budi Pramono', 52),
(17, 2, '30456096', 'SMP Bijak Kecamatan Hehe', 'SMP', 'Negeri', 'Jl. DI Panjaitan No. 13, Kelurahan Cucu, Kecamatan Hehe', 'Kelurahan Cucu', 'Kecamatan Hehe', 'Slamet Panjaitan', 50),
(18, 2, '30450227', 'SMA Hebat Kecamatan Hehe', 'SMA', 'Negeri', 'Jl. H. Agus Salim No. 39, Kelurahan Haha, Kecamatan Hehe', 'Kelurahan Haha', 'Kecamatan Hehe', 'Raka Hendra Wibowo', 44),
(19, 2, '30404066', 'SMA Hebat Kecamatan Hehe A', 'SMA', 'Negeri', 'Jl. Wahid Hasyim No. 35, Kelurahan Cici, Kecamatan Hehe', 'Kelurahan Cici', 'Kecamatan Hehe', 'Yusuf Galih Subakti', 61),
(20, 2, '30409129', 'SMK Bisa Kecamatan Hehe', 'SMK', 'Negeri', 'Jl. Otto Iskandardinata No. 101, Kelurahan Coco, Kecamatan Hehe', 'Kelurahan Coco', 'Kecamatan Hehe', 'Yanto Setiawan', 54),
(21, 3, '30432285', 'SD Cornell Kecamatan Lala', 'SD', 'Negeri', 'Jl. Gajah Mada No. 5, Kelurahan Lulu, Kecamatan Lala', 'Kelurahan Lulu', 'Kecamatan Lala', 'Taufik Yusuf Haryanto', 52),
(22, 3, '30455588', 'SD Cornell Kecamatan Lala A', 'SD', 'Negeri', 'Jl. Mulawarman No. 17, Kelurahan Nono, Kecamatan Lala', 'Kelurahan Nono', 'Kecamatan Lala', 'Galih Panjaitan', 50),
(23, 3, '30478424', 'SD Stanford Kecamatan Lala', 'SD', 'Swasta', 'Jl. Antasari No. 24, Kelurahan Nono, Kecamatan Lala', 'Kelurahan Nono', 'Kecamatan Lala', 'Yanto Aldi Haryanto', 59),
(24, 3, '30444319', 'SD Berkeley Kecamatan Lala', 'SD', 'Negeri', 'Jl. Pemuda No. 8, Kelurahan Nono, Kecamatan Lala', 'Kelurahan Nono', 'Kecamatan Lala', 'Wawan Aditya Herianto', 50),
(25, 3, '30479279', 'SD Columbia Kecamatan Lala', 'SD', 'Negeri', 'Jl. Gatot Subroto No. 115, Kelurahan Nana, Kecamatan Lala', 'Kelurahan Nana', 'Kecamatan Lala', 'Hendra Raka Nainggolan', 51),
(26, 3, '30418328', 'SMP Juara Kecamatan Lala', 'SMP', 'Negeri', 'Jl. M. Yamin No. 36, Kelurahan Nene, Kecamatan Lala', 'Kelurahan Nene', 'Kecamatan Lala', 'Heri Surya Kurniawan', 52),
(27, 3, '30433956', 'SMP Hits Kecamatan Lala', 'SMP', 'Negeri', 'Jl. RE Martadinata No. 31, Kelurahan Nene, Kecamatan Lala', 'Kelurahan Nene', 'Kecamatan Lala', 'Guntur Taufik Mahendra', 45),
(28, 3, '30498360', 'SMA Koboh Kecamatan Lala', 'SMA', 'Negeri', 'Jl. Cipto Mangunkusumo No. 98, Kelurahan Nana, Kecamatan Lala', 'Kelurahan Nana', 'Kecamatan Lala', 'Anwar Saputra', 47),
(29, 3, '30451215', 'SMA Harapan Kecamatan Lala', 'SMA', 'Negeri', 'Jl. M. Yamin No. 100, Kelurahan Lulu, Kecamatan Lala', 'Kelurahan Lulu', 'Kecamatan Lala', 'Yusuf Pratama', 45),
(30, 3, '30429759', 'SMK Kreatif Kecamatan Lala', 'SMK', 'Swasta', 'Jl. Untung Suropati No. 39, Kelurahan Nene, Kecamatan Lala', 'Kelurahan Nene', 'Kecamatan Lala', 'Aditya Dani Santoso', 52),
(31, 4, '30402756', 'SD Cornell Kecamatan Koko', 'SD', 'Negeri', 'Jl. Gajah Mada No. 62, Kelurahan Ruru, Kecamatan Koko', 'Kelurahan Ruru', 'Kecamatan Koko', 'Yusuf Sari', 52),
(32, 4, '30469915', 'SD MIT Kecamatan Koko', 'SD', 'Negeri', 'Jl. M. Yamin No. 90, Kelurahan Kiki, Kecamatan Koko', 'Kelurahan Kiki', 'Kecamatan Koko', 'Wawan Pasaribu', 59),
(33, 4, '30483582', 'SD Columbia Kecamatan Koko', 'SD', 'Negeri', 'Jl. Bung Tomo No. 109, Kelurahan Riri, Kecamatan Koko', 'Kelurahan Riri', 'Kecamatan Koko', 'Fajar Robby Kuswanto', 44),
(34, 4, '30439519', 'SD MIT Kecamatan Koko A', 'SD', 'Swasta', 'Jl. S. Parman No. 117, Kelurahan Kuku, Kecamatan Koko', 'Kelurahan Kuku', 'Kecamatan Koko', 'Dani Wahyu Kuswanto', 52),
(35, 4, '30429611', 'SD Cornell Kecamatan Koko A', 'SD', 'Swasta', 'Jl. Mulawarman No. 137, Kelurahan Riri, Kecamatan Koko', 'Kelurahan Riri', 'Kecamatan Koko', 'Akbar Dharmawan', 48),
(36, 4, '30499896', 'SMP Kece Kecamatan Koko', 'SMP', 'Negeri', 'Jl. Yos Sudarso No. 32, Kelurahan Riri, Kecamatan Koko', 'Kelurahan Riri', 'Kecamatan Koko', 'Taufik Fajar Sembiring', 49),
(37, 4, '30454812', 'SMP Cerdas Kecamatan Koko', 'SMP', 'Negeri', 'Jl. DI Panjaitan No. 82, Kelurahan Ruru, Kecamatan Koko', 'Kelurahan Ruru', 'Kecamatan Koko', 'Tio Muhammad Wijaya', 58),
(38, 4, '30444496', 'SMA Harapan Kecamatan Koko', 'SMA', 'Swasta', 'Jl. Otto Iskandardinata No. 18, Kelurahan Kuku, Kecamatan Koko', 'Kelurahan Kuku', 'Kecamatan Koko', 'Yusuf Wijaya', 37),
(39, 4, '30409956', 'SMA Prestasi Kecamatan Koko', 'SMA', 'Negeri', 'Jl. H. Agus Salim No. 115, Kelurahan Riri, Kecamatan Koko', 'Kelurahan Riri', 'Kecamatan Koko', 'Rian Fajar Lestari', 59),
(40, 4, '30446098', 'SMK Mahir Kecamatan Koko', 'SMK', 'Swasta', 'Jl. Gajah Mada No. 7, Kelurahan Roro, Kecamatan Koko', 'Kelurahan Roro', 'Kecamatan Koko', 'Dani Eka Ramadhan', 49),
(41, 5, '30424837', 'SD Oxford Kecamatan Titi', 'SD', 'Negeri', 'Jl. Yos Sudarso No. 103, Kelurahan Toto, Kecamatan Titi', 'Kelurahan Toto', 'Kecamatan Titi', 'Fahmi Aris Supriadi', 56),
(42, 5, '30478150', 'SD Princeton Kecamatan Titi', 'SD', 'Negeri', 'Jl. DI Panjaitan No. 48, Kelurahan Yoyo, Kecamatan Titi', 'Kelurahan Yoyo', 'Kecamatan Titi', 'Rian Adit Budiman', 61),
(43, 5, '30472147', 'SD Cornell Kecamatan Titi', 'SD', 'Negeri', 'Jl. Kadrie Oening No. 44, Kelurahan Toto, Kecamatan Titi', 'Kelurahan Toto', 'Kecamatan Titi', 'Rian Situmorang', 47),
(44, 5, '30409643', 'SD Princeton Kecamatan Titi A', 'SD', 'Negeri', 'Jl. AW Syahranie No. 16, Kelurahan Yuyu, Kecamatan Titi', 'Kelurahan Yuyu', 'Kecamatan Titi', 'Roni Fikri Wicaksono', 40),
(45, 5, '30498548', 'SD MIT Kecamatan Titi', 'SD', 'Swasta', 'Jl. DI Panjaitan No. 6, Kelurahan Sisi, Kecamatan Titi', 'Kelurahan Sisi', 'Kecamatan Titi', 'Fahmi Agus Herianto', 40),
(46, 5, '30463851', 'SMP Bijak Kecamatan Titi', 'SMP', 'Swasta', 'Jl. Gajah Mada No. 101, Kelurahan Yuyu, Kecamatan Titi', 'Kelurahan Yuyu', 'Kecamatan Titi', 'Yudi Subagyo', 54),
(47, 5, '30411689', 'SMP Cerdas Kecamatan Titi', 'SMP', 'Negeri', 'Jl. Juanda No. 112, Kelurahan Sisi, Kecamatan Titi', 'Kelurahan Sisi', 'Kecamatan Titi', 'Andi Dedi Rajagukguk', 46),
(48, 5, '30454451', 'SMA Maju Kecamatan Titi', 'SMA', 'Swasta', 'Jl. Bhayangkara No. 68, Kelurahan Tutu, Kecamatan Titi', 'Kelurahan Tutu', 'Kecamatan Titi', 'Surya Zainal Dharmawan', 52),
(49, 5, '30461035', 'SMA Prestasi Kecamatan Titi', 'SMA', 'Negeri', 'Jl. Basuki Rahmat No. 116, Kelurahan Yoyo, Kecamatan Titi', 'Kelurahan Yoyo', 'Kecamatan Titi', 'Yudi Ramadhan', 58),
(50, 5, '30490150', 'SMK Trampil Kecamatan Titi', 'SMK', 'Negeri', 'Jl. Bhayangkara No. 141, Kelurahan Sisi, Kecamatan Titi', 'Kelurahan Sisi', 'Kecamatan Titi', 'Muhammad Zainal Panggabean', 51),
(51, 6, '30437884', 'SD Cornell Kecamatan Gogo', 'SD', 'Negeri', 'Jl. Juanda No. 40, Kelurahan Wiwi, Kecamatan Gogo', 'Kelurahan Wiwi', 'Kecamatan Gogo', 'Tri Purwanto', 51),
(52, 6, '30440187', 'SD MIT Kecamatan Gogo', 'SD', 'Negeri', 'Jl. Gajah Mada No. 107, Kelurahan Wawa, Kecamatan Gogo', 'Kelurahan Wawa', 'Kecamatan Gogo', 'Indra Aldi Setiawan', 30),
(53, 6, '30441353', 'SD MIT Kecamatan Gogo A', 'SD', 'Negeri', 'Jl. KH. Harun Nafsi No. 126, Kelurahan Wowo, Kecamatan Gogo', 'Kelurahan Wowo', 'Kecamatan Gogo', 'Agus Reza Rajagukguk', 57),
(54, 6, '30438744', 'SD Harvard Kecamatan Gogo', 'SD', 'Negeri', 'Jl. DI Panjaitan No. 48, Kelurahan Gigi, Kecamatan Gogo', 'Kelurahan Gigi', 'Kecamatan Gogo', 'Rian Galih Lestari', 43),
(55, 6, '30481633', 'SD Stanford Kecamatan Gogo', 'SD', 'Swasta', 'Jl. PM Noor No. 79, Kelurahan Gugu, Kecamatan Gogo', 'Kelurahan Gugu', 'Kecamatan Gogo', 'Wawan Hadi', 56),
(56, 6, '30440415', 'SMP Pintar Kecamatan Gogo', 'SMP', 'Negeri', 'Jl. KH. Abul Hasan No. 72, Kelurahan Wiwi, Kecamatan Gogo', 'Kelurahan Wiwi', 'Kecamatan Gogo', 'Arif Ahmad Dharmawan', 58),
(57, 6, '30494975', 'SMP Pintar Kecamatan Gogo A', 'SMP', 'Swasta', 'Jl. RE Martadinata No. 24, Kelurahan Wiwi, Kecamatan Gogo', 'Kelurahan Wiwi', 'Kecamatan Gogo', 'Adit Yusuf Tarigan', 39),
(58, 6, '30403085', 'SMA Unggul Kecamatan Gogo', 'SMA', 'Negeri', 'Jl. Aminah Syukur No. 138, Kelurahan Wiwi, Kecamatan Gogo', 'Kelurahan Wiwi', 'Kecamatan Gogo', 'Reza Agus Firmansyah', 44),
(59, 6, '30407414', 'SMA Harapan Kecamatan Gogo', 'SMA', 'Negeri', 'Jl. RE Martadinata No. 146, Kelurahan Gugu, Kecamatan Gogo', 'Kelurahan Gugu', 'Kecamatan Gogo', 'Bambang Dimas Hidayat', 68),
(60, 6, '30441205', 'SMK Bisa Kecamatan Gogo', 'SMK', 'Negeri', 'Jl. Sultan Alimuddin No. 64, Kelurahan Wowo, Kecamatan Gogo', 'Kelurahan Wowo', 'Kecamatan Gogo', 'Roni Heri Subagyo', 48),
(61, 7, '30435300', 'SD Yale Kecamatan Jojo', 'SD', 'Negeri', 'Jl. KH. Abul Hasan No. 14, Kelurahan Koko, Kecamatan Jojo', 'Kelurahan Koko', 'Kecamatan Jojo', 'Surya Guntur Haryanto', 43),
(62, 7, '30494511', 'SD Princeton Kecamatan Jojo', 'SD', 'Swasta', 'Jl. PM Noor No. 8, Kelurahan Koko, Kecamatan Jojo', 'Kelurahan Koko', 'Kecamatan Jojo', 'Aldi Harahap', 46),
(63, 7, '30422167', 'SD Yale Kecamatan Jojo A', 'SD', 'Negeri', 'Jl. Kadrie Oening No. 85, Kelurahan Juju, Kecamatan Jojo', 'Kelurahan Juju', 'Kecamatan Jojo', 'Andi Slamet Pratama', 54),
(64, 7, '30456233', 'SD Yale Kecamatan Jojo B', 'SD', 'Negeri', 'Jl. S. Parman No. 47, Kelurahan Koko, Kecamatan Jojo', 'Kelurahan Koko', 'Kecamatan Jojo', 'Raka Nasution', 45),
(65, 7, '30455422', 'SD Stanford Kecamatan Jojo', 'SD', 'Negeri', 'Jl. Bung Tomo No. 108, Kelurahan Juju, Kecamatan Jojo', 'Kelurahan Juju', 'Kecamatan Jojo', 'Agus Simanjuntak', 48),
(66, 7, '30459140', 'SMP Kece Kecamatan Jojo', 'SMP', 'Negeri', 'Jl. KH. Abul Hasan No. 51, Kelurahan Kaka, Kecamatan Jojo', 'Kelurahan Kaka', 'Kecamatan Jojo', 'Slamet Wicaksono', 48),
(67, 7, '30404671', 'SMP Bijak Kecamatan Jojo', 'SMP', 'Negeri', 'Jl. M. Yamin No. 124, Kelurahan Jiji, Kecamatan Jojo', 'Kelurahan Jiji', 'Kecamatan Jojo', 'Budi Dedi Putra', 56),
(68, 7, '30421675', 'SMA Harapan Kecamatan Jojo', 'SMA', 'Swasta', 'Jl. Aminah Syukur No. 7, Kelurahan Keke, Kecamatan Jojo', 'Kelurahan Keke', 'Kecamatan Jojo', 'Abdi Eka Prasetyo', 54),
(69, 7, '30407284', 'SMA Maju Kecamatan Jojo', 'SMA', 'Negeri', 'Jl. Antasari No. 13, Kelurahan Kaka, Kecamatan Jojo', 'Kelurahan Kaka', 'Kecamatan Jojo', 'Dian Saefullah', 65),
(70, 7, '30489842', 'SMK Inovatif Kecamatan Jojo', 'SMK', 'Negeri', 'Jl. Kadrie Oening No. 128, Kelurahan Koko, Kecamatan Jojo', 'Kelurahan Koko', 'Kecamatan Jojo', 'Ahmad Tio Irawan', 40),
(71, 8, '30486096', 'SD Oxford Kecamatan Bibi', 'SD', 'Negeri', 'Jl. Sultan Alimuddin No. 84, Kelurahan Bobo, Kecamatan Bibi', 'Kelurahan Bobo', 'Kecamatan Bibi', 'Tio Limbong', 51),
(72, 8, '30472864', 'SD Cornell Kecamatan Bibi', 'SD', 'Negeri', 'Jl. M. Yamin No. 58, Kelurahan Bubu, Kecamatan Bibi', 'Kelurahan Bubu', 'Kecamatan Bibi', 'Dian Anwar Pratama', 61),
(73, 8, '30455815', 'SD Princeton Kecamatan Bibi', 'SD', 'Negeri', 'Jl. Otto Iskandardinata No. 9, Kelurahan Bobo, Kecamatan Bibi', 'Kelurahan Bobo', 'Kecamatan Bibi', 'Ahmad Ramadhan', 34),
(74, 8, '30401551', 'SD MIT Kecamatan Bibi', 'SD', 'Negeri', 'Jl. Slamet Riyadi No. 119, Kelurahan Bubu, Kecamatan Bibi', 'Kelurahan Bubu', 'Kecamatan Bibi', 'Muhammad Raka Hadi', 48),
(75, 8, '30488104', 'SD Oxford Kecamatan Bibi A', 'SD', 'Negeri', 'Jl. Antasari No. 61, Kelurahan Bubu, Kecamatan Bibi', 'Kelurahan Bubu', 'Kecamatan Bibi', 'Muhammad Indra Siregar', 43),
(76, 8, '30458614', 'SMP Kece Kecamatan Bibi', 'SMP', 'Swasta', 'Jl. Bhayangkara No. 6, Kelurahan Bobo, Kecamatan Bibi', 'Kelurahan Bobo', 'Kecamatan Bibi', 'Bintang Angga Supriadi', 41),
(77, 8, '30445021', 'SMP Bijak Kecamatan Bibi', 'SMP', 'Negeri', 'Jl. S. Parman No. 84, Kelurahan Fafa, Kecamatan Bibi', 'Kelurahan Fafa', 'Kecamatan Bibi', 'Fajar Subakti', 46),
(78, 8, '30479904', 'SMA Jaya Kecamatan Bibi', 'SMA', 'Negeri', 'Jl. Otto Iskandardinata No. 121, Kelurahan Fafa, Kecamatan Bibi', 'Kelurahan Fafa', 'Kecamatan Bibi', 'Joko Saefullah', 55),
(79, 8, '30456339', 'SMA Jaya Kecamatan Bibi A', 'SMA', 'Swasta', 'Jl. Antasari No. 28, Kelurahan Fifi, Kecamatan Bibi', 'Kelurahan Fifi', 'Kecamatan Bibi', 'Raka Saputra', 51),
(80, 8, '30419804', 'SMK Mandiri Kecamatan Bibi', 'SMK', 'Negeri', 'Jl. S. Parman No. 61, Kelurahan Fifi, Kecamatan Bibi', 'Kelurahan Fifi', 'Kecamatan Bibi', 'Yanto Raka Mahendra', 52),
(81, 9, '30465317', 'SD Yale Kecamatan Zaza', 'SD', 'Negeri', 'Jl. Slamet Riyadi No. 123, Kelurahan Lele, Kecamatan Zaza', 'Kelurahan Lele', 'Kecamatan Zaza', 'Fajar Galih Pohan', 50),
(82, 9, '30491933', 'SD Cornell Kecamatan Zaza', 'SD', 'Negeri', 'Jl. Sultan Alimuddin No. 21, Kelurahan Zozo, Kecamatan Zaza', 'Kelurahan Zozo', 'Kecamatan Zaza', 'Roni Kuswanto', 63),
(83, 9, '30446572', 'SD Columbia Kecamatan Zaza', 'SD', 'Swasta', 'Jl. Antasari No. 65, Kelurahan Zizi, Kecamatan Zaza', 'Kelurahan Zizi', 'Kecamatan Zaza', 'Galih Dian Rosidi', 42),
(84, 9, '30433490', 'SD Stanford Kecamatan Zaza', 'SD', 'Negeri', 'Jl. AW Syahranie No. 110, Kelurahan Zozo, Kecamatan Zaza', 'Kelurahan Zozo', 'Kecamatan Zaza', 'Dani Rian Ginting', 43),
(85, 9, '30416492', 'SD Oxford Kecamatan Zaza', 'SD', 'Negeri', 'Jl. S. Parman No. 7, Kelurahan Lele, Kecamatan Zaza', 'Kelurahan Lele', 'Kecamatan Zaza', 'Rudi Bayu Mulyono', 50),
(86, 9, '30493943', 'SMP Gaul Kecamatan Zaza', 'SMP', 'Negeri', 'Jl. Bhayangkara No. 51, Kelurahan Zizi, Kecamatan Zaza', 'Kelurahan Zizi', 'Kecamatan Zaza', 'Yudi Fajar Rosidi', 52),
(87, 9, '30433661', 'SMP Keren Kecamatan Zaza', 'SMP', 'Negeri', 'Jl. Kadrie Oening No. 105, Kelurahan Lala, Kecamatan Zaza', 'Kelurahan Lala', 'Kecamatan Zaza', 'Dian Saefullah', 48),
(88, 9, '30495115', 'SMA Hebat Kecamatan Zaza', 'SMA', 'Swasta', 'Jl. Antasari No. 147, Kelurahan Zozo, Kecamatan Zaza', 'Kelurahan Zozo', 'Kecamatan Zaza', 'Dwi Simanjuntak', 53),
(89, 9, '30400250', 'SMA Maju Kecamatan Zaza', 'SMA', 'Negeri', 'Jl. Pahlawan No. 112, Kelurahan Lala, Kecamatan Zaza', 'Kelurahan Lala', 'Kecamatan Zaza', 'Faisal Limbong', 42),
(90, 9, '30445007', 'SMK Trampil Kecamatan Zaza', 'SMK', 'Swasta', 'Jl. Mulawarman No. 101, Kelurahan Lala, Kecamatan Zaza', 'Kelurahan Lala', 'Kecamatan Zaza', 'Agus Rian Pratama', 57),
(91, 10, '30481323', 'SD Yale Kecamatan Shisha', 'SD', 'Negeri', 'Jl. KH. Abul Hasan No. 35, Kelurahan Shishi, Kecamatan Shisha', 'Kelurahan Shishi', 'Kecamatan Shisha', 'Aris Rizal Nainggolan', 56),
(92, 10, '30417683', 'SD Oxford Kecamatan Shisha', 'SD', 'Negeri', 'Jl. RE Martadinata No. 118, Kelurahan Shushu, Kecamatan Shisha', 'Kelurahan Shushu', 'Kecamatan Shisha', 'Surya Heri Kusuma', 46),
(93, 10, '30462748', 'SD Yale Kecamatan Shisha A', 'SD', 'Negeri', 'Jl. Pemuda No. 62, Kelurahan Shishi, Kecamatan Shisha', 'Kelurahan Shishi', 'Kecamatan Shisha', 'Gilang Fikri Wicaksono', 43),
(94, 10, '30469996', 'SD Berkeley Kecamatan Shisha', 'SD', 'Negeri', 'Jl. Bhayangkara No. 77, Kelurahan Tatas, Kecamatan Shisha', 'Kelurahan Tatas', 'Kecamatan Shisha', 'Adit Dedi Rosidi', 50),
(95, 10, '30411588', 'SD Yale Kecamatan Shisha B', 'SD', 'Negeri', 'Jl. KH. Harun Nafsi No. 127, Kelurahan Tatas, Kecamatan Shisha', 'Kelurahan Tatas', 'Kecamatan Shisha', 'Muhammad Anwar Haryanto', 48),
(96, 10, '30430351', 'SMP Juara Kecamatan Shisha', 'SMP', 'Swasta', 'Jl. Gajah Mada No. 55, Kelurahan Shushu, Kecamatan Shisha', 'Kelurahan Shushu', 'Kecamatan Shisha', 'Bambang Dian Ginting', 47),
(97, 10, '30436788', 'SMP Kece Kecamatan Shisha', 'SMP', 'Negeri', 'Jl. H. Agus Salim No. 73, Kelurahan Titis, Kecamatan Shisha', 'Kelurahan Titis', 'Kecamatan Shisha', 'Gilang Bambang Purwanto', 57),
(98, 10, '30466694', 'SMA Koboh Kecamatan Shisha', 'SMA', 'Negeri', 'Jl. Otto Iskandardinata No. 89, Kelurahan Shushu, Kecamatan Shisha', 'Kelurahan Shushu', 'Kecamatan Shisha', 'Joko Gilang Mahendra', 59),
(99, 10, '30463845', 'SMA Prestasi Kecamatan Shisha', 'SMA', 'Negeri', 'Jl. Untung Suropati No. 32, Kelurahan Tatas, Kecamatan Shisha', 'Kelurahan Tatas', 'Kecamatan Shisha', 'Surya Nainggolan', 58),
(100, 10, '30489594', 'SMK Inovatif Kecamatan Shisha', 'SMK', 'Negeri', 'Jl. Wahid Hasyim No. 113, Kelurahan Tatas, Kecamatan Shisha', 'Kelurahan Tatas', 'Kecamatan Shisha', 'Aditya Anwar Pasaribu', 59);

